# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

# Stable configurations
edition = "2018"
max_width = 100
merge_derives = true
use_field_init_shorthand = true
use_try_shorthand = true
